### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by ongraphpythondev**
Updated requirements for pipenv installation.

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Thank you for the pull request. Shouldn't we also use >= for all the other packages ?

The problem with Travis CI does not come from your change, it can be fixed this way: https://github.com/Pierre-Sassoulas/django-zxcvbn-password-validator/commit/71e438bbda72ec387c53983e9fda79a2f0ddff32.

**Comment by Pierre-Sassoulas** [comment]
I will modify the other requirements myself. Do you need a new pypi release with the changes?

**Comment by ongraphpythondev** [comment]
Yes, if you can provide us.

**Comment by Pierre-Sassoulas** [comment]
I published 1.3.8 to pypi, let me know if it works for you.

**Pull request merged**
