### PR TITLE
Make sankey optional

### LINKED ISSUE #94: Make pySankeyBeta dependency optional
Installing pySankeyBeta brings a lot of heavy dependencies (numpy, scipy, pandas) but I guess those are only needed if you want to create sankey diagrams.

Using the mechanism provided in pep0508, it would be possible to make the dependency optional and to use something like `pip install django-survey-and-report[sankey]` to install it.

What do you think?

### PR DESCRIPTION
**Pull request by quimey**
This is a possible way to fix #94. We are going to be use this fork, but if you are interested we could merge this (I could put some more work on it if you think it can be improved).

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
This look good, I think it just need a little documentation on the way it's installed to not have pysankey on the user side ? Or maybe I should release two packages and I'm the one who should read about how to do that ?

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by quimey** [comment]
This change will make the default not to include pysankey and an extra package to include it. I'm not sure how that integrates with pypi but if installing from github you can do:
```
pip install git+git://github.com/quimey/django-survey#egg=django-survey-and-report
```
to get the "reduced version" with no pysankey and 
```
pip install git+git://github.com/quimey/django-survey#egg=django-survey-and-report[sankey]
```
to include them.

I agree that this should be added to documentation but I wanted to hear your thoughts about it first.

**Comment by Pierre-Sassoulas** [comment]
Hmm it sound really nice. I did not know you could do that even for real install (I'm using this for tests dependency with locale install). Would it work with the pypi package too with `pip install django-survey-and-report` and `pip install django-survey-and-report[sankey]` ?

**Comment by quimey** [comment]
It should work. Django does it (for different reasons). See:
https://docs.djangoproject.com/en/3.0/topics/auth/passwords/#using-argon2-with-django
and
https://github.com/django/django/blob/master/setup.cfg#L52

**Comment by Pierre-Sassoulas** [comment]
Ho, that's very nice, you taught me something I'll use a lot. Also, I'll definitely merge this, very easy to use and intuitive.

**Pull request merged**
