### PR TITLE
Adding Japanese translation

### PR DESCRIPTION
**Pull request by nsuzue**
Thank you for your letting me do Japanese translation. I have checked my translation is working properly on my environment but please feel free to ask me additional modification if you find something wrong.

In addition, since I found a kind of bug while working on this, I will post a new issue within next a couple of days after I check if it is really a bug.

Thank you,
Nobu

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Dômo arigatô :)

I'm really grateful for this. I will be able to review and accept the pull
request by tuesday 17. I'm currently on a wifi (in fact in Tokyo ;) ) and
cannot do anything properly from my cellphone.

Do not hesitate to make another pull request in the meantime.

**Comment by nsuzue** [comment]
Hello,

In addition to Japanese translation, I added another patch that outputs "form" instead of "field" in "question.html" file to print select tag properly. However, looking at the history of the file, you seem to have changed same part to print "field" instead of "form." So, although it looked working properly in my brief test, I am not completely sure if my change makes sense.  If there is any conflict, please discard the patch.

Thank you.

**Comment by Pierre-Sassoulas** [comment]
Hello,

The japanese translation looks really good. Good job ! I added the authorship in the po file and will merge it. 

Also, sorry I forgot that you can't create two pull request at the same time. I will remove the other commit  from this PR so it stays about translation only. Regarding this other commit, it will be trickier to check. While the model and lower level logic is tested and should work well in most case, the interface is a part of the code that is not tested much and probably need some changes right now. Let's talk about it here : https://github.com/Pierre-Sassoulas/django-survey/issues/11.

Thank you again.

**Comment by Pierre-Sassoulas** [comment]
This was merged manually [here](https://github.com/Pierre-Sassoulas/django-survey/commit/56661e43cb522192b4b9125223fd936b7bf39aba). Thank you for you work and welcome to the project :)

**Comment by nsuzue** [comment]
Thank you for merging my translation. And, about the issue of missing select tag, to be honest, I don't completely understand the mechanism of rendering questions, so I will take time to have better understanding about it, and then will post a possible solution or a question to the issue #11.

Thank you.

**Pull request closed without merging**
