### PR TITLE
Check answers for integer and float

### PR DESCRIPTION
**Pull request by g-normand**

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Looks reasonable thank you ! Could you add covering tests for it, please ?

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Thank you for adding tests ! The current issue with the pipeline is due to a function that became too complex `` survey/models/answer.py:57:5: C901 'Answer.check_answer_body' is too complex (14)``. Would you mind doing a refactor first ?

Maybe a visitor pattern like:
```python
def check_answer_body(self, question, body):
    func = getattr("check_answer_body_for_{question.type.lower()}")
    return func(question, body)


def check_answer_body_for_integer(self, question, body):    
    if body and body != "":
        try:
            body = int(body)
        except ValueError:
            msg = "Answer is not an integer"
            raise ValidationError(msg)
```

**Comment by g-normand** [comment]
@Pierre-Sassoulas I changed a little bit the function :)
Let me know if it's ok or not

**Review by Pierre-Sassoulas — APPROVED** [review]
Thank you for refactoring 👍

**Comment by Pierre-Sassoulas** [comment]
I released this in 1.4.4 it should be available shortly.

**Comment by g-normand** [comment]
Perfect, thanks :)

**Pull request merged**
